import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import Providers from "./providers/Providers"
// import Navbar from "./components/Navbar"
import dynamic from "next/dynamic"

const Navbar = dynamic(() => import("./components/Navbar"), { ssr: false })
import { AuthUserLoader } from "./components/AuthUserLoader"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
//${geistSans.variable} ${geistMono.variable}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative`}>
        <Toaster />
        <Providers>
          <AuthUserLoader>
            <Navbar />
            <div className="mt-20 relative ">{children}</div>
          </AuthUserLoader>
        </Providers>
      </body>
    </html>
  )
}
